project:
  type: website
  output-dir: docs

website:
  title: "UCHC HPC"
  favicon: img/favicon.png
  sidebar:
    style: "docked"
    logo: img/cbc.png
    search: true
    collapse-level: 1
    contents:
      - text: "About"
        href: about.qmd
      
      # - text: "Intro to HPC"
      #   href: intro.qmd

      - text: "Getting Started"
        href: starting.qmd

      - text: "Account & Password"
        href: account.qmd
      
      - section: "Connecting"
        href: connect.qmd
        contents:
        - text: "Overview"
          href: connect.qmd
        - text: "Open OnDemand"
          href: ondemand.qmd
        - text: "Command Line"
          href: cli.qmd
        - text: "SSH Keys"
          href: keys.qmd
        - text: "VPN"
          href: vpn.qmd
        # - text: "Two Factor"
        #   href: twofactor.qmd

      - text: "File Systems & Storage"
        href: storage.qmd

      - text: "Running Jobs" 
        href: running.qmd

      - text: "Transferring Data"
        href: transfer.qmd
      
      - text: "Software"
        href: software.qmd
      
      - text: "Databases"
        href: databases.qmd
      
      # - text: "File Permissions"
      #   href: permissions.qmd

      # - text: "Best Practices"
      #   href: bestpractices.qmd

      - text: "Get Help"
        href: help.qmd

      # - text: "Miscellaneous"
      #   href: misc.qmd

format:
  html:
    theme: 
      light: [flatly, src/custom.scss]
    toc: true
    # include-in-header:
      # - text: <script src="src/toggle.js"></script>



