project:
  type: website
  output-dir: docs

website:
  title: "UCHC HPC"
  favicon: img/favicon.png
  sidebar:
    style: "docked"
    logo: img/cbc.png
    search: true
    contents:

      - text: "Account & Password"
        href: account.qmd
      
      - text: "Connecting"
        href: connect.qmd

      - text: "File System & Storage"
        href: storage.qmd

      - text: "Job Submission" 
        href: submission.qmd

      - text: "Transferring Data"
        href: transfer.qmd
      
      - text: "Software"
        href: software.qmd
      
      - text: "Command Line Interface"
        href: cli.qmd
      
      - text: "File Permissions"
        href: permissions.qmd
      
      - text: "Databases"
        href: databases.qmd

      - text: "Best Practices"
        href: bestpractices.qmd

      - text: "Miscellaneous"
        href: misc.qmd
      
      - text: "Quick Reference"
        href: quick.qmd

      - text: "Get Help"
        href: help.qmd

format:
  html:
    theme: 
      light: flatly
    toc: true
    include-in-header:
      - text: <script src="src/toggle.js"></script>



