project:
  type: website
  output-dir: docs

website:
  title: "UConn HPC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - quickstart.qmd
      - advanced.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



