# Requesting an Account
In order to use the Mantis cluster, you must request a **CAM account**. It is referred to as a CAM account because much of the administration of the Mantis cluster, in addition to other systems, is handled by the [Center for Cell Analysis and Modeling at UConn Health](https://health.uconn.edu/cell-analysis-modeling/).

To request a CAM account:

1. Submit an [account request ticket](https://health.uconn.edu/high-performance-computing/contact/).
2. Select `New Account Request` from the `Request Type` dropdown menu.
3. Choose `HPC Cluster Account` as the `Account Type`. 
4. Fill in all relevant and required fields and click submit.

Once your request is approved, you will receive an email with your account information. This will include a username which is different from your NetID and a temporary password.

# Passwords
Upon approval of an account request, you will need to enroll in the [CAM Password Manager](https://password.cam.uchc.edu/) and reset your password.

Passwords expire every 90 days.

Any time you need to reset your password, you can do so in the [CAM Password Manager](https://password.cam.uchc.edu/).

::: {.callout-important}
If you are ever not able to login or transfer files, ensure that you don't have an expired password.
:::

::: {.callout-warning}
Do not share your password with anyone! **We will never ask you for your password for any reason.**
:::


<!--  
According to Ion, having access, regardless of mode, is dependent on:
1. You have a valid SSH key pair using an acceptable encryption algorithm in your home folder .ssh subfolder
2. Your home folder, .ssh subfolder, and SSH key files have proper ownership and access restrictions
3. Your account is not locked
4. Your account is not disabled
5. Your account does not have an expired password
6. Your account does not require change-password-on-next-logon

Is it possible to login to globus with invalid password?
-->