---
title: "Connecting to Mantis"
---

<!-- Once you have created a CAM Account there are two ways to connect to the Mantis cluster which are documented on this page:
1. Open OnDemand: a web-based interface for accessing
2. SSH (Secure Shell): a command-line interface

# Open OnDemand -->


# SSH (Secure Shell)
Users can connect to the Mantis cluster through a command-line interface using SSH.

## Quick Reference
Login hosts are listed below. If you need more details, skip to the next section. 

We have two login hosts:

- `login.hpc.cam.uchc.edu`
  - The recommended host.
  - Accessible externally (doesn't require VPN or UCHC secure WiFI). 
  - This host is not accessible through the CAM VPN.
- `mantis-submit.cam.uchc.edu`
  - Not recommended unless the other is down or in specific circumstances where VPN is needed.
  - This host is only available when connected to the [CAM VPN](#cam-vpn) or a UCHC secure WiFi network.

## Using SSH
Logging in through SSH requires:

1. [A CAM account](#cam-account)
2. [An SSH client](#ssh-client)
3. [An SSH key pair](#ssh-keys) 
4. [Connecting through the login.cam.uchc.edu host](#using-ssh)

## 1. CAM Account
See the [account page](accounts.qmd) for details on obtaining a CAM account


## 2. SSH Client
#### MacOS & Linux
MacOS and Linux users can use the built-in SSH client through the `Terminal` application. 

#### Windows
Since Windows 10, Windows comes with a built-in SSH client which can be accessed through the `Windows PowerShell` application. For older versions of Windows, you can use a third-party SSH client such as [MobaXterm](https://mobaxterm.mobatek.net). 


## 3. SSH Keys
Before being able to login with your SSH client, you will need to setup SSH keys. SSH keys are a secure authentication method that can be used for remote access to a server without using passwords. It is in fact a more secure authentication method than using a password. SSH keys consist of a pair of cryptographic keys --- a private key kept secret on your computer and a public key placed on the remote server you want to access. Only ed25519 keys are accepted.

### Create SSH keys
You can create a public and private SSH key pair using your SSH client in `Windows PowerShell` or a MacOS / Linux `Terminal`.  

1. First check for an existing SSH key pair by running the following command: 

::: {.panel-tabset}
#### MacOS / Linux Terminal
```bash
ls ~/.ssh/
```

#### Windows PowerShell
```bash
ls $env:USERPROFILE\.ssh\
```
:::

If you see files named `id_ed25519.pub` and `id_ed25519`, you already have an SSH key pair and can skip ahead to the [Copy to Mantis](#copy-public-ssh-key-to-mantis) section. If you do not see these files, you will need to create a new SSH key pair.

2. To create a key pair run the following command:

```bash
ssh-keygen -t ed25519 -C <comment>
```

Replacing `<comment>` with something to help you identify which computer this key pair was created for. For example: `laptop`

3. You will be prompted to specify the location to save the key. You can press enter to accept the default location.
4. Next you will be prompted to create a passphrase which is optional. If you don't wish to create a passphrase, simply press enter.

::: {.callout-warning}
Do not share your private key with anyone! Your private key should be kept secret and secure on your computer. If someone else has access to your private key, they can access the Mantis cluster as you. **We will never ask you for your private key for any reason.**
:::


### Copy Public SSH Key to Mantis
Once you have created your SSH key pair, you will need to copy the public key to the Mantis cluster.

In order to do so you must first connect to the [CAM VPN](#cam-vpn) or be using a UCHC secure WiFi network.

::: {.panel-tabset}
### MacOS and Linux
On MacOS and Linux, you can copy your public key to the Mantis cluster using the `ssh-copy-id` command:

```bash
ssh-copy-id <user>@transfer.cam.uchc.edu
```

Where `<user>` is changed to your CAM username.

When prompted, enter your CAM password. Note that for security reasons, your cursor will remain stationary and you will not see any characters appear as you type your password. Note that passwords expire every 90 days and can be reset in the [CAM Password Manager](https://pm-app.cam.uchc.edu/portal/Home/LandingPage).

### Windows PowerShell
On Windows 10 or later, you can copy your public key to the Mantis cluster with `Windows PowerShell` using the command:

```bash
type $env:USERPROFILE\.ssh\id_ed25519.pub | ssh <user>@transfer.cam.uchc.edu "mkdir -p .ssh && cat >> .ssh/authorized_keys"
```

Where `<user>` is changed to your CAM username.

When prompted, enter your CAM password. Note that for security reasons, your cursor will remain stationary and you will not see any characters appear as you type your password. Note that passwords expire every 90 days and can be reset in the [CAM Password Manager](https://pm-app.cam.uchc.edu/portal/Home/LandingPage).

:::


## 4. Connecting with SSH
Once you have copied your public SSH key to the Mantis cluster, you can connect using the SSH client.

To connect to Mantis through SSH, open a `Windows PowerShell` or `Terminal` window and enter the following command:

```bash
ssh <user>@login.hpc.cam.uchc.edu
```

Where `<user>` is changed to your CAM username.

When connecting through this host, you will be redirected to one of several login nodes.

::: {.callout-warning}
When connecting to Mantis over SSH, you will be connected to a submit node, also known as login node. Please do not run anything on these nodes that is computationally demanding as this can negatively impact other users who are also connecting to these nodes. To do real work, submit a [batch job](running.qmd#batch-job-submission) or initiate an [interactive session](running.qmd#interactive-job). Long running or intensive processes running on login nodes may be killed without notice. This includes some software installations such as when using `Conda` or compiling code. When in doubt, it is best to submit a batch job or initiate an interactive session.
:::

::: {.callout-note}
`login.hpc.cam.uchc.edu` cannot be used when you are connected to the CAM VPN. You will be able to connect initially but will lose the connection shortly after.
:::

# CAM VPN
<!--TODO: Move the documentation for vnp here eventually? -->

To connect to the CAM VPN, follow the instructions [here](https://health.uconn.edu/high-performance-computing/tutorials/cam-vpn/). 

::: {.callout-note}
Note that the CAM VPN is distinct from the University of Connecticut VPN. 
:::

### Why is it called the CAM VPN?
The administration of the Mantis cluster is handled by staff in the Cell Analysis and Modeling (CAM) department at the University of Connecticut Health Center.



<!-- # SSH Tunnelling -->
<!-- TODO: Explain why you might need this and how to do it. -->
<!-- TODO: How will this change once all traffic must go through external host? -->


<!-- # X11 Forwarding -->
<!-- TODO: Why you might need this and how to do it. -->
<!-- TODO: How will this change once all traffic must go through external host? -->



# Internal Host
There is an additional host that can be used to connect to the Mantis cluster. This host is only accessible through the CAM VPN or through a UCHC secure WiFi network. We don't recommend using this host for regular use and it may be decommisioned in the future. There are specific use cases such as when you need to use the CAM VPN where the other host does not currently allow connections. For example if you need to establish an SSH tunnel to a compute node. This host can also be used if the other is down.

To login, use the command: `ssh <user>@mantis-submit.cam.uchc.edu`

When connecting through this host, you will be redirected to one of several login nodes.
