# Storage Policies
This page summarizes storage policies and management practices on the UConn Health HPC. For more information about the file systems and storage locations available on the cluster, please see the [storage page](storage.qmd). 

## Managed Storage
### /seqdata
This location is used for storing raw sequencing data and is intended to alleviate strain on quotas in other locations and to discourage data duplication. Data are stored as read-only. All data generated by the CGI sequencing core are stored here by default. You may request that other raw data be stored here, but CBC will have to move it there for you, as users do not have write access. 

If you would like to move existing raw data to this location or store data from an external sequencing center, please contact us at `cbcsupport@helpspotmail.com`.

Raw sequence data will be stored here for a period of **2 years**. After this time, data will be moved to a long-term archival system. Details regarding this archival system are still being finalized, but users will be able to request that data be moved back to `/seqdata` for a period of time if they need to actively use the the data again for analyses.  

**Do not copy data from this directory**. For convenience, consider making a symlink to files stored here. By avoiding unnecessary copying, accidental data corruption or deletion can be avoided and space will be used more efficiently on the cluster and within directories you own. 

### /scratch
Files will automatically be removed from `/scratch` after 90 days. If you have files in `/scratch` that you would like to keep, please move them to another location before this time.

### /tmp
Any files in `/tmp` belonging to a user without an active job on a node may be removed at any time. 

## User Managed Storage
All other user data is managed by users and will never be modified by HPC administrators. These locations are subject to storage quota limits. Requests can be made to increase the default quotas for `\lab`, `\projects`, and `\department`. To request a quota increase, please [submit a ticket](https://bioinformatics.uconn.edu/contact-us/bioinformatics-technical-issues/). 

| Location | Quota |
|----------|-------|
| /home/FCAM/\<user\> | 2 TB |
| /labs | 2 TB |
| /projects | 2 TB |
| /department | 2 TB |

